### ISSUE TITLE
Isort incorrectly reorders import above comment

### ISSUE THREAD

**Issue by steckhelena** [PyCQA/isort#1532]
On isort `VERSION 5.5.4`

If I sort the following file:
```python
"""
Configuration database loader.
"""


#
# IMPORTS
#
from pymongo.errors import OperationFailure
from pymongo.errors import ServerSelectionTimeoutError
from pymongo import MongoClient
from typing import Mapping
```

I get the following output:

```diff
 """
 
 
+from pymongo import MongoClient
 #
 # IMPORTS
 #
 from pymongo.errors import OperationFailure
 from pymongo.errors import ServerSelectionTimeoutError
-from pymongo import MongoClient
 from typing import Mapping
```

I have the following config file:
```toml
[tool.isort]
force_single_line = "True"
from_first = "True"
force_alphabetical_sort = "True"
lines_between_types = 1
lines_after_imports = 2
```

I don't think this behaviour is intended, especially because in other files without a module docstring it works as expected.
Btw, this works if I have the `treat-all-comment-as-code` option set, but the inconsistency still exists only in this case(which the comment is not in the first line of the file) if it is not set.
Thanks!
