### ISSUE TITLE
pre-commit hook not picking up cython pyx files

### ISSUE THREAD

**Issue by paddyroddy** [PyCQA/isort#1601]
my `.pre-commit-config.yaml` is as per the docs
```
repos:
    - repo: https://github.com/pycqa/isort
      rev: 5.6.4
      hooks:
          - id: isort
            name: isort (python)
            args: ["--profile", "black"]
          - id: isort
            name: isort (cython)
            types: [cython]
```
I have a `*.pyx` file but when I run the `pre-commit` hook it doesn't seem to find the file. My isort version is `5.6.4`

![image](https://user-images.githubusercontent.com/15052188/100003676-6535e880-2dbe-11eb-872b-b4bfb2cb6843.png)

**Comment by MarcoGorelli** [comment]
have you staged your .pyx file?

**Comment by paddyroddy** [comment]
no I hadn't... sorry my bad

**Comment by MarcoGorelli** [comment]
no worries :rofl: 

btw, [pre-commit 2.9.0 adds support for `types_or`](https://github.com/pre-commit/pre-commit/releases/tag/v2.9.0), so you could do
```
repos:
    - repo: https://github.com/pycqa/isort
      rev: 5.6.4
      hooks:
          - id: isort
            name: isort
            types: [text]
            types_or: [python, cython]
            args: ["--profile", "black"]
```
