### ISSUE TITLE
black and isort conflict unless line length copy/pasta

### ISSUE THREAD

**Issue by Akuli** [PyCQA/isort#1743]
pyproject.toml:

```toml
[tool.black]
line-length = 100
skip-magic-trailing-comma = true
skip-string-normalization = true

[tool.isort]
#line_length = 100   # Uncomment to fix
profile = "black"
multi_line_output = 3
```

isort wants:

```python
from typing import (
    TYPE_CHECKING,
    Any,
    Callable,
    Iterator,
    List,
    Optional,
    Tuple,
    overload,
)
```

black wants:

```python
from typing import TYPE_CHECKING, Any, Callable, Iterator, List, Optional, Tuple, overload
```

You can copy/paste the same line length to both configs but it would be nice if `profile = "black"` would read it from black's config. Or is that not how profiles work?
