### ISSUE TITLE
Comments in group imports are moved to a single line causing line too long violation (black, flake8)

### ISSUE THREAD

**Issue by 1oglop1** [PyCQA/isort#1852]
Hi,
this issue seems to be related to #1009 #1843.

When using `isort` as a pre-commit hook with `black` profile. My commented imports are being moved to a single line.

Commented imports are intentional because I have some work in progress but I'd still like to commit (without `--no-verify`)

Example:
Before:
```python
from dj_rest_auth.views import (
    LoginView,
    LogoutView,
    # PasswordChangeView,
    # PasswordResetConfirmView,
    # PasswordResetView,
    # UserDetailsView,
)
```

After:
```
from dj_rest_auth.views import (  # PasswordChangeView,; PasswordResetConfirmView,; PasswordResetView,; UserDetailsView,
    LoginView,
    LogoutView,
)
```

My pre-commit hook configuration:
```yaml
# isort
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

        name: isort (python)
        args: &isort_args
          - --line-length=100
          - --profile=black
          - --combine-as
          - --lines-after-imports=2
          - --src-path=app
      - id: isort
        name: isort (cython)
        types: [ cython ]
        args: *isort_args
      - id: isort
        name: isort (pyi)
        types: [ pyi ]
        args: *isort_args
```

I tried to use black flags `# fmt: off ... # fmt: on` but that had no effect.
