### ISSUE TITLE
`isort` ignores config files like `pyproject.toml` when explicitly passing files

### ISSUE THREAD

**Issue by lucaslie** [PyCQA/isort#1872]
I noticed that `isort` ignores config files as soon as any arguments are passed in on the command line. 

Is this really the desired behavior? Especially when `isort` is called on a specific file only it is very counterintuitive that config files like `pyproject.toml` are ignored, i.e., 

```bash
isort <some-folder>/some_file.py
```

will ignore my toml file at `./pyproject.toml` while

```bash
isort
```

will load the configuration from the toml file. 

I have noticed this discrepancy while using `isort` with the `pre-commit` framework. Depending on how `pre-commit` is called it might actually call the tools individually on each file, e.g., when called via `pre-commit run --from-ref main --to-ref HEAD`. In this case `isort` won't load the configuration. 

This is unlike most other linting/quality check tools like `flake8`, `black`, or `pylint` that will still load the configuration files.

**Comment by timothycrosley** [comment]
This is not isort's behavior intended behavior, and would represent a bug. isort is coded and tested to behave in this way the same as all other linting / formatting tools you mention. Can you provide some more information about what you are seeing?

**Comment by timothycrosley** [comment]
In particular, if you could demonstrate in a repo or docker machine exactly the behavior you are seeing in a reproducible way. The only way isort wouldn't pick up a config file, in the given examples by design, is if the settings file lives outside of either a repository that the source file is in, or does not live in a parent directory of the file (unlike the given example) which is the same behavior exhibited by these other tools. 

Is there any chance you are using an older version of isort?

**Comment by pawel-ch** [comment]
In my tests isort ignores **pyproject.toml** regardless the files being passed.

Example **pyproject.toml**:

```toml
[tool.poetry]
name = "isort_test"
version = "0.1.0"
description = ""
authors = ["Python Developer <developer@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
line_length = 120
profile = "black"
reverse_relative = 1
src_paths = ["."]
```

**bash**

```bash
poetry install
poetry run isort . --show-config | less  # search for line_length and you will find 79
```

This also causes false positives, when using pre-commit:

**.pre-commit-config.yaml**

```yaml
exclude: 'docs|node_modules|.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
```

**bash**

```bash
pre-commit run --all-files
```
