### ISSUE TITLE
Specify/exclude files the same ways as black or "use from black"

### ISSUE THREAD

**Issue by swaldhoer** [PyCQA/isort#1888]
I think it would be good if one could specify the included/excluded files in the same way as black does it:

```toml
[tool.isort]
include = '\.pyi?$'
extend-exclude = '''
/(
  | bla/data
  | blub
)/
'''
```

I would be even better if you could just say *just use these settings from black*, like e.g., something like that

```toml
[tool.isort]
profile = "black"
[tool.isort.black]
include = true
extend-exclude = true
exclude = true
```
