### ISSUE TITLE
`lines_before_import` adds newlines above module's docstring when used with `float_to_top`

### ISSUE THREAD

**Issue by gbolmier** [PyCQA/isort#1935]
Using MacOS, python `3.7.11`, isort `5.10.1`, and the following config in `pyproject.toml`:

```toml
[tool.isort]
lines_before_imports = 1
float_to_top = true
```

Before running `isort tmp.py`:

```python
"""
Tmp module.
"""
import os
os.getcwd()
```

After:

```python
  
"""
Tmp module.
"""

import os

os.getcwd()
```

(note the added leading empty line)
