### ISSUE TITLE
Incorrect sorting when using "as" keyword in import statement

### ISSUE THREAD

**Issue by chrisk314** [PyCQA/isort#1952]
I have a set of import statements from a single package with one using an `as` statement. The correct sorting of the import statements is as below.

```python
from my.package.channel import (
    Channel,
    ChannelFactory,
    Edge,
    LocalChannelFactory,
    MultiprocessingChannelFactory,
)
from my.package.channel import ChannelIdService as cid_svc
```

`isort` incorrectly sorts the statements as below.

```python
from my.package.channel import (
    Edge,
    LocalChannelFactory,
    MultiprocessingChannelFactory,
)
from my.package.channel import Channel, ChannelFactory
from my.package.channel import ChannelIdService as cid_svc
```

OS: ubuntu 20.04
Python: 3.7.7
isort: 5.10.1

**Comment by andersk** [comment]
> `isort` incorrectly sorts the statements as below.

isort gives me

```python
from my.package.channel import Channel, ChannelFactory
from my.package.channel import ChannelIdService as cid_svc
from my.package.channel import (
    Edge,
    LocalChannelFactory,
    MultiprocessingChannelFactory,
)
```

(with `--profile=black -n 80`) which is still unexpected, but at least alphabetical. I’m curious what your configuration is?

[Ruff](https://github.com/charliermarsh/ruff) instead combines all the non-`as` imports from the same module into one statement, then sorts the statements. It would be nice to make this consistent between Ruff and isort, and I think Ruff’s behavior makes more sense.

```python
from my.package.channel import (
    Channel,
    ChannelFactory,
    Edge,
    LocalChannelFactory,
    MultiprocessingChannelFactory,
)
from my.package.channel import ChannelIdService as cid_svc
```

**Comment by chrisk314** [comment]
Here's the config for `isort` and `black` present in my `pyproject.toml`. It's modified from my actual project for the placeholder python package name used in my original issue report. I just confirmed that the behaviour is still the same on the latest isort v5.11.2.

```toml
[tool.isort]
profile = "black"
src_paths = ["src/my/package"]
multi_line_output = 3
force_grid_wrap = 0
wrap_length = 100
line_length = 100
use_parentheses = true
include_trailing_comma = true
force_sort_within_sections = true
sort_relative_in_force_sorted_sections = true
lines_after_imports = 2
order_by_type = false
case_sensitive = false
reverse_relative = true
sections = ["FUTURE","STDLIB","THIRDPARTY","FIRSTPARTY","APPLICATION","LOCALFOLDER"]
no_lines_before = "LOCALFOLDER"
known_application = ["my.package"]
known_first_party = ["my"]
extend_skip = ["_version.py", "versioneer.py"]
extend_skip_glob = ["docs/*", "*venv*/*"]

[tool.black]
line-length = 100
include = '(src\/.*\.py|tests\/.*\.py|setup.py)'
extend-exclude = '(.*\/_version.py|.*venv.*\/.*)'
```

I wasn't aware of `ruff`. It looks nice. Will give it a try.
