### ISSUE TITLE
Publish an official isort image on Docker Hub

### ISSUE THREAD

**Issue by ryboe** [PyCQA/isort#1959]
Please publish an official image for `isort` on [Docker Hub](https://hub.docker.com/), [AWS Public ECR](https://gallery.ecr.aws/), [GCR](https://cloud.google.com/container-registry/), the GitHub Container Registry, or some other equivalent registry. This will make it easier to use `isort` in CI pipelines. I'm currently using a third-party [`kiwicom/isort`](https://hub.docker.com/r/kiwicom/isort) image, but it's out of date and inherently not as trustworthy as an official image.

For reference, [here's the official image for the `black` code formatter](https://hub.docker.com/r/pyfound/black).

Here's an example of how I use `kiwicom/isort` in a GitLab CI pipeline:

```yaml
Isort:
  image:
    name: kiwicom/isort:5.7.0
  script:
    - isort --version
    - isort --check-only app
```
