### ISSUE TITLE
Not compatible with Black

### ISSUE THREAD

**Issue by zheyuanWang** [PyCQA/isort#1963]
According to [official link](https://pycqa.github.io/isort/docs/configuration/black_compatibility.html), 
I am using the following pre-commit-config:
```
repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
```
However, for this file, isort's output is 
```python
from ..builder import (DETECTORS, build_backbone, build_head, build_map_to_bev,
                       build_neck, build_segmentor, build_voxel_encoder,)
```
while Black's output is:
```python
from ..builder import (
    DETECTORS,
    build_backbone,
    build_head,
    build_map_to_bev,
    build_neck,
    build_segmentor,
    build_voxel_encoder,
)
```

Different output, so the pre-commit check would never pass.

**Comment by RickLucassen** [comment]
Hey, would like to point out that the following fixes this for me: https://github.com/PyCQA/isort/pull/1876
Adding the "split_on_trailing_comma" configuration solves this, since this has not been released yet it means you would have to install isort from github.

**Comment by andersk** [comment]
You must not be invoking `isort` correctly. With your pre-commit configuration I get

```console
$ cat test.py
from ..builder import (DETECTORS, build_backbone, build_head, build_map_to_bev,
                       build_neck, build_segmentor, build_voxel_encoder,)

$ pre-commit run --all
isort....................................................................Failed
- hook id: isort
- files were modified by this hook

Fixing /tmp/test/test.py

black....................................................................Passed

$ cat test.py
from ..builder import (
    DETECTORS,
    build_backbone,
    build_head,
    build_map_to_bev,
    build_neck,
    build_segmentor,
    build_voxel_encoder,
)
```

as expected.

If you’d also like to be able to invoke `isort test.py` directly (not via `pre-commit`), then you need to configure it in `.isort.cfg` or `pyproject.toml` ([documentation](https://pycqa.github.io/isort/docs/configuration/options.html)) rather than `.pre-commit-config.yaml`.

**Comment by zheyuanWang** [comment]
> @zheyuanWang should be fixed in 5.11.0, can you check?

Yes it worked!

changing the version of isort solved conflicts.

```
repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
```
