### ISSUE TITLE
skip fails on Windows

### ISSUE THREAD

**Issue by phw** [PyCQA/isort#1983]
When using `skip` to skip a specific file inside a directory this fails on Windows.

E.g. I had this in my `pyproject.toml`:

```toml
[tool.isort]
skip = ["src/resources.py"]
```

On Linux this ignored the file `src/resources.py`, on Windows it failed. Same result when using a backslash (`skip = ['src\resources.py']`). Maybe something is broken in regards to comparing normalized paths.

As a workaround using `skip_glob` (just using the single file, no globbing patterns) instead works:

```toml
[tool.isort]
skip_glob = ["src/resources.py"]
```
