### ISSUE TITLE
pre-commit run -a and a normal commit behave differently

### ISSUE THREAD

**Issue by 12rambau** [PyCQA/isort#2006]
I'm using `isort` in my pre-commit hooks for a while. I wanted to update my CD/CI by using github action and specifically [pre-commit/action@v3.0.0](https://github.com/pre-commit/action) which is running `pre-commit run -a`. 

My problem is that it's not behaving the same way as a regular commit, making my CD/CI to fail everytime. 

my `.isort.cfg`:

```
[settings]
profile=black
skip=sepal_ui/sepalwidgets/__init__.py
skip_glob=**/.ipynb_checkpoints/*, **__pycache__/*
src_paths=sepal_ui
```

and my pre-commit config:

```
repos:
  - repo: 'https://github.com/psf/black'
    rev: 22.3.0
    hooks:
      - id: black
        stages: [commit]
  - repo: 'https://github.com/pycqa/flake8'
    rev: 3.9.2
    hooks:
      - id: flake8
        stages: [commit]
  - repo: 'https://github.com/commitizen-tools/commitizen'
    rev: v2.18.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: 'https://github.com/pycqa/isort'
    rev: 5.10.1
    hooks:
      - id: isort
        stages: [commit]
  - repo: 'https://github.com/kynan/nbstripout'
    rev: 0.5.0
    hooks:
      - id: nbstripout
        stages: [commit]
```

Is it normal ? is it a bug ? 

PS: I searched the issue tracker and found this one that may be related https://github.com/PyCQA/isort/issues/1623 but I'm not using a `toml` file for my configuration.
