### ISSUE TITLE
Isort is incompatible with black

### ISSUE THREAD

**Issue by sashko1988** [PyCQA/isort#2046]
Isort doesn't truly support trailing commas. Or, to be more specific, it doesn't support it as black does.

I use a trailing comma whenever I need to import more than one function from a module.
In this case, it's easier to track the changes in git whenever someone adds a new function from the same module or removes the existing one. It seems easy when there are only 2 functions, but imagine 5 or 6 functions that still fit in an 88symbol line length. 

**.pre-commit-config.yaml content:**
```yaml
repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.11.2
    hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    - id: black
      args: ["--line-length=120"]
```

**Initial content of check.py**
```python
from some_mod import (Dialect, DictReader, DictWriter, bingo, hardcas, go_go, and_o,)

if __name__ == "__main__":
    pass
```

**Black format output:**
```python
$pre-commit run black --file check.py && cat check.py
black....................................................................Passed

from some_mod import (
    Dialect,
    DictReader,
    DictWriter,
    bingo,
    hardcas,
    go_go,
    and_o,
)

if __name__ == "__main__":
    pass
```

**Isort format output:** (same result for both initial content of check.py and after it was formatted with black)
```python
$pre-commit run isort --file check.py && cat check.py
isort....................................................................Passed

from some_mod import Dialect, DictReader, DictWriter, and_o, bingo, go_go, hardcas

if __name__ == "__main__":
    pass
```

The problem is that it even changes the already formatted files

**Comment by timothycrosley** [comment]
You are not using standard black, but black with one customization: ` args: ["--line-length=120"]` isort will be compatible, if you specify the same line length for it

**Comment by sashko1988** [comment]
@timothycrosley, but what does Isort have to do with the actual Black run args? 

1. Isort doesn't check the black section of the pre-commit config file, and Isort only looks at its own config that is stored under the black profile.
2. the problem is not the line length, but that **isort doesn't support trailing commas as expected**. i.e., it makes the same formatting as the Black would with a trailing comma.

If the import statement has the trailing comma, isort should format it as Black would or shouldn't touch it if it has an expected format already(with parenthesis and a function per line)


Let's put it another way. I have several files formatted like this:
```python
cat check.py
from some_mod import (
    Dialect,
    DictReader,
    DictWriter,
    and_o,
    bingo,
    go_go,
    hardcase,
)

if __name__ == "__main__":
    pass
```

With a new trailing comma feature, I expect the isort doesn't change the format of the import section. so initial format == expected. But isort does a change:
```python
$pre-commit run isort --file check.py && cat check.py
isort....................................................................Passed

from some_mod import Dialect, DictReader, DictWriter, and_o, bingo, go_go, hardcase

if __name__ == "__main__":
    pass
```

And, just in case, I removed the line length arg for black from the black config, so we won't argue about it anymore.
```yaml
$cat .pre-commit-config.yaml

repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.11.2
    hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    - id: black
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      additional_dependencies: [
        "flake8-bugbear",
        "flake8-comprehensions",
        "flake8-debugger",
        "flake8-pep3101",
        "flake8-simplify",
        "pep8-naming"
      ]
      args: ["--max-line-length=88","--extend-ignore=E203"]
```
