### ISSUE TITLE
isort gets confused when working with git worktrees

### ISSUE THREAD

**Issue by mknaranja** [PyCQA/isort#2068]
If I work with git worktrees isort (used as pre-commit hook) gets confused and identifies first party library code in the worktree as third party library.

I use
```
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort
```

What I do is:

```
git clone REPOSITORY.git
cd REPOSITORY
git worktree add ../REPOSITORY_WORKTREE BRANCH_WORKTREE
cd ../REPOSITORY_WORKTREE
pre-commit run --all
```

What it then does from:

```
import THIRDPARTY

import OWNCODE
```

is

```
import OWNCODE
import THIRDPARTY
```

or

```
import THIRDPARTY
import OWNCODE
```
