### ISSUE TITLE
black profile conflicts with black

### ISSUE THREAD

**Issue by jceresini** [PyCQA/isort#2070]
Using the following version, I noticed that running `black` and `isort --profile=black` back-to-back results in conflicting changes

black==22.12.0
isort==5.11.4
Python 3.9.6

Using this minimal python file:

```
from google.api_core.exceptions import AlreadyExists, BadRequest, ClientError, Conflict, NotFound
```

When I run `black minimal.py` it changes the file to:

```
from google.api_core.exceptions import (
    AlreadyExists,
    BadRequest,
    ClientError,
    Conflict,
    NotFound,
)
```

And then if I run `isort --profile=black minimal.py` it reverts to the first example.

I have a CI job that tests the code with both black and isort using the black profile, but noticed this particular code couldn't satisfy both tools. I just applied this CI job (which I use in many other places) to an older code-base, so I can't tell if the behavior is new, or if its related to specific versions of either black or isort.

**Comment by jceresini** [comment]
I did some testing and I see the same behavior with the black version 22.10.0 and 22.8.0 and isort versions 5.10.1, and 5.9.3.

By "same behavior" i mean all 3 versions of black format the file the same way, and all 3 versions of isort format the file the same way, both sets of which conflict

**Comment by parafoxia** [comment]
I'm not able to reproduce this issue on either Python 3.9.11 or 3.11.1 using the same isort and black versions as you. Are black and isort using different configurations? Maybe conflicting pypeoject.toml files/settings?

**Comment by jtwalsh0** [comment]
I was having a similar problem. I rebuilt my environment and it worked.

**Comment by ajnelson-nist** [comment]
Hello,

This appears to still be a problem.  I am seeing it occur in fresh `pre-commit` environments.

The environments are using this `.pre-commit-config.yaml` file:

```yaml
repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - --extend-ignore=E203,E501
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args:
          - --profile black
```

`isort` and `black` are in consistent disagreement on how to handle many-symbol imports.

May this issue be re-opened?

**Comment by grabov** [comment]
I have the same problem.

```
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.11
```
