### ISSUE TITLE
isort is not run on save in VS Code anymore

### ISSUE THREAD

**Issue by ddahan** [PyCQA/isort#2099]
On all my Python projects, I noticed isort is not called anymore when I save a Python file (when I run isort from the CLI, it works).

I can't understand what's causing this because I changed nothing in my settings. I suspect a version upgrade of VS Code or isort (it's not a Python upgrade issue), or maybe a conflict with black (which still works as expected by the way).

Note that I never used the Microsoft isort extension as I never needed it (auto-sorting does not require this extension).

PS: I know this may be related to VS Code rather than isort itself, but I had no idea where else to post this :/

Here are my main settings:

**pyproject.toml**
```toml
[tool.poetry.dev-dependencies]
black = "*" 
isort = "*"

[tool.black]
line-length = 90
target-version = ['py311']
preview = true

[tool.isort]
py_version = 311
profile = "black"
src_paths = [
    "dj_apps",
    "dj_config",
] # https://stackoverflow.com/a/64769646/2255491
known_django = "django"
sections = [
    "FUTURE",
    "STDLIB",
    "DJANGO",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER",
]
no_lines_before = ["LOCALFOLDER"]
extend_skip = ["migrations"]
```

**VS Code settings**
```json
"editor.formatOnSave": true,
"python.languageServer": "Pylance",
"python.pythonPath": "/usr/local/bin/python",
"python.linting.enabled": true,
"python.formatting.provider": "black",
"python.formatting.blackPath": "/usr/local/bin/black",
"python.analysis.autoImportCompletions": true,
"python.analysis.importFormat": "absolute",
"python.analysis.indexing": true,
"python.analysis.packageIndexDepths": [
    {
        "name": "django",
        "depth": 10,
        "includeAllSymbols": true
    }
],
"python.analysis.extraPaths": [
    "${workspaceFolder}/dj_apps"
],
"[python]": {
    "editor.tabSize": 4,
    "editor.codeActionsOnSave": {
        "source.organizeImports": true
    }
}
```

**EDIT** : i just noticed VS Code comes with an embedded version of isort 5.10.1 which is NOT the isort I installed and want to use. I suspect there could be a conflict between both versions. Anyway, watching VS Code isort logs, saving a file has no effect on this version neither:

<img width="588" alt="image" src="https://user-images.githubusercontent.com/1933516/219757891-3e2eebb6-8ccf-45e9-89d4-57f140b3ce02.png">

I added `"isort.path": [ "/usr/local/bin/isort"]` to settings to point to the right 5.12.0 version. It works in vs code logs, but still, nothing happens on save.

Thanks for your help
