### ISSUE TITLE
How to use `import_headings` option?

### ISSUE THREAD

**Issue by joe733** [PyCQA/isort#2110]
In my `pyproject.toml` I have:

```toml
[tool.isort]
ensure_newline_before_comments = true
force_grid_wrap = 0
force_sort_within_sections = true
import_headings = { STDLIB = "standard", THIRDPARTY = "external", FIRSTPARTY = "local" }
include_trailing_comma = true
length_sort = true
line_length = 100
multi_line_output = 3
reverse_sort = true
reverse_relative = true
use_parentheses = true
```

**Actual Output**

```python
from urllib.parse import urlsplit
from functools import lru_cache
import re

import pytest

from .hostname import hostname
from .utils import validator
```

**Expected Output**

```python
# standard
from urllib.parse import urlsplit
from functools import lru_cache
import re

# external
import pytest

# local
from .hostname import hostname
from .utils import validator
```

What am I missing?

**Comment by joe733** [comment]
[Documentation](https://pycqa.github.io/isort/docs/configuration/options.html#import-headings) does not provide an example.

**Comment by anirudnits** [comment]
Hello @joe733, thanks for raising this issue! I looked into it and it  turns out you have to declare the headings like this:

`
import_heading_stdlib = "standard"
import_heading_thirdparty = "external"
import_heading_firstparty = "local"
`

and it would do the trick. I do understand that there isn't adequate documentation surrounding this and I would take up the task to add this in the docs.

Let me know if you have any other concerns.

**Comment by joe733** [comment]
Hi @anirudnits, that worked!

```toml
import_heading_stdlib = "standard"
import_heading_thirdparty = "external"
import_heading_localfolder = "local"
```

Thank you. Do you want to keep this issue (labeled `question/documentation`) open? Or shall I close it?
