### ISSUE TITLE
Feature request: Make new executable "icheck"

### ISSUE THREAD

**Issue by homm** [PyCQA/isort#2160]
First of all, thanks for the great tool, I really like to use it in every Python project.

I understand the main idea that first of all `isort` is a tool for automatically fixing imports. The problem is it often used to check a source code on CI. And this is how typical `.github/workflows/check.yaml` looks like:

```yml
on: [push]
jobs:
  build:
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install -r requirements.txt
      - run: pytest
      - run: isort --diff --check .
      - run: flake8
```

So, other tools like `flake8` and `pytest` works out of the box with no arguments. In opposite, `isort` does nothing when it is bare called. In the best case, users have to google again and again how to call it properly or even use it misconfigured when it always succeeded.

I understand how hard will be change the default behaviour to at least return non-zero code without `--check` argument, even in a next major release. So my proposal is to add another executable script especially for CI called `icheck`, which will do the same as `isort --diff --check .`

I believe it will greatly improve usability of this tool.
