### ISSUE TITLE
Incorrect sorting

### ISSUE THREAD

**Issue by nyudenkov** [PyCQA/isort#2170]
isort sorts third-party socketio to local imports.

Before:
```python
import jwt
from socketio.exceptions import ConnectionRefusedError

from src.core.auth import auth_backend
```

After:
```python
import jwt

from socketio.exceptions import ConnectionRefusedError
from src.core.auth import auth_backend
```

My guess is that it can be because of the socketio module in the src directory:
```
├── src
   └── socketio
```

In pre-commit config:
```
- repo: https://github.com/timothycrosley/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: [--profile, black]
```
