### ISSUE TITLE
 Feature request: per-block sorting strategy (inline sort)

### ISSUE THREAD

**Issue by Freso** [PyCQA/isort#2272]
Similar to https://github.com/PyCQA/isort/issues/785 I am in a situation where I would like to do `no_inline_sort` only for `LOCALFOLDER`.

Being able to define this as
```toml
[tool.isort.local_folder]
no_inline_sort = true
```
and doing settings there would be great.

I guess `no_inline_sort_local_folder` could also work, but it feels like an endless amount of `$option_$section` options.
