### ISSUE TITLE
[WARNING] repo `https://github.com/pycqa/isort` uses deprecated stage names (commit, merge-commit, push) which will be removed in a future version.  Hint: often `pre-commit autoupdate --repo https://github.com/pycqa/isort`

### ISSUE THREAD

**Issue by BaseMax** [PyCQA/isort#2332]
```
[WARNING] repo `https://github.com/pycqa/isort` uses deprecated stage names (commit, merge-commit, push) which will be removed in a future version.  Hint: often `pre-commit autoupdate --repo https://github.com/pycqa/isort` will fix this.  if it does not -- consider reporting an issue to that repo.
```

My config:

```
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: run isort (python)
        description: a Python utility / library to sort imports
```

![Image](https://github.com/user-attachments/assets/ddc9f37b-a2de-4766-a607-ff807ae3e0cc)
